.TH MBIDLED "1" "May 2022"
.SH NAME
mbidled \- run command on mailbox change
.
.SH SYNOPSIS
.
.B mbidled
.B \-c
.I MBSYNC_CONFIG
[\fB-e\fR \fICOMMAND\fR]
.RI [ OPTION ]...
.
.SH DESCRIPTION
.B mbidled
runs
.I
COMMAND
on mailbox change.
.
.P
.BR "CAUTION!" " Program has not been tested outside author's setup. Use it with care."
.
.SH COMMANDS
.P
.TP
.BI \-c\  MBSYNC_CONFIG
Path to
.BR mbsync (1)
configuration file to use.
.
.TP
.BI \-e\  COMMAND
Execute shell
.I
COMMAND
on mailbox change.
.
.IP
By default, synchronize changed mailbox:
.BR "mbsync -c $MBIDLED_CONFIG $MBIDLED_CHANNEL:$MBIDLED_MAILBOX" .
.
.IP
The following environment variables are set for the executed program:
.TS
tab(|)[];
ll.
Variable|Value
$\fBMBIDLED_CONFIG\fR|Argument for \fB-c\fR.
$\fBMBIDLED_CHANNEL\fR|Name of changed Channel.
$\fBMBIDLED_MAILBOX\fR|Name of changed mailbox.
.TE
.
.TP
.B \-v
Be verbose. Note that output may contain sensitive information.
.
.TP
.B \-h
Display help and exit.
.
.SH STORES
.B mbidled
can watch for mailbox changes in the following stores.
.
.SS IMAP
IMAP configuration is read from
.B IMAPAccount
sections.
.
.P
IMAP4 IDLE command is used (RFC 2177) to watch for changes in
.B INBOX
and all mailboxes in
.B INBOX.
namespace.
.
.SS Maildir
Mailboxes having prefix of
.B MaildirStore.Path
and
.B MaildirStore.Inbox
are being watched.
.
.P
Filesystem is being watched using
.BR inotify (7)
on Linux systems (if supported) or using periodic
.BR stat (2)
calls in all other cases (refer to libev for exact details).
.
.SH CONFIGURATION
.B mbidled
has been designed to use configuration file (format) of
.BR mbsync .
.
.P
Besides standard configuration options
.BR mbidled
recognizes some extra options.
All such extension options start with a comment marker character
.RB ( # )
so they are completely ignored by
.BR mbsync .
Prefix (part before colon) is case-sensitive.
.
.SS Global
.TP
.B "#MBIDLED:StrictPropagate [None|Far|Near|Both]
Changes from stores can be registered during the execution of
.I COMMAND
but it cannot be known whether change has been properly handled by the program
or maybe it had completely missed it. For this reason, command is scheduled for
a re-run to make sure it knows about latest updates. However, in the vast
majority of cases this second run would likely be a no-op, because this change
is often generated by the started program itself.
This option specifies which sides of the channel should
schedule a new command run upon a change (thus propagating potential changes).
Optimal choice between safety and low server load can be if for
.BR PullNew " or " PushNew ,
.BR Far " or " Near
specified for this option, respectively, that means side where new mails come
from is surely re-checked.
(Default=Both)
.
.TP
.BI "#MBIDLED:StartTimeout " time
After registering a change wait this
.I time
of seconds
before starting
.IR COMMAND .
Stores may emit multiple change notifications for the
same change event thus it can be useful to wait a bit.
(Default=1)
.
.TP
.BI "#MBIDLED:StartInterval " time
Do not run
.I COMMAND
more often than this
.I time
of seconds.
(Default=30)
.
.TP
.BR "#MBIDLED:Option" " ..."
Process line as if there would be no prefix given. Can be useful to
tweak some options exclusively for
.BR mbidled .
.
.IP
Examples:
.IP
.EX
# Disable watching channel.
#MBIDLED:Sync None

# Watch specific mailboxes only.
#MBIDLED:Patterns Archive Sent
.EE
.
.SH "SEE ALSO"
.B mbsync(1)
